### PR TITLE
[WIP] rename ObjectMeta field to fix decoding issues

### PR DESCRIPTION
**Pull request by asymmetric**
workaround for a ugoji bug, see https://github.com/kubernetes/client-go/issues/8#issuecomment-285333502

### CODE REVIEW

**Comment by asymmetric** [comment]
Testing this on aws-operator, will merge if it works.

**Comment by rossf7** [comment]
@asymmetric LGTM lets try this. Approving the test with `aws-operator` since we can't repro locally.

**Comment by rossf7** [comment]
@asymmetric can we close this? We're prioritising the k8s 1.6 upgrade which hopefully will make this less painful!

**Comment by asymmetric** [comment]
YES!

**Pull request closed without merging**
